import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SITE_ORIGIN="https://ozdalmete-netizen.github.io";const MAX_BODY_BYTES=128*1024;
const EXPECTED_TURNSTILE_HOSTNAME=new URL(SITE_ORIGIN).hostname.toLowerCase();const TURNSTILE_TIMEOUT_MS=5000;
const cors={"Access-Control-Allow-Origin":SITE_ORIGIN,"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});
const db=()=>createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
async function sha256Hex(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function randomToken(){const b=crypto.getRandomValues(new Uint8Array(32));let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
function requestIp(req:Request){return req.headers.get("cf-connecting-ip")||req.headers.get("x-real-ip")||req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown"}
async function rateKey(req:Request){const salt=Deno.env.get("RATE_LIMIT_SALT")||"humanity1-reservation";return sha256Hex(`${salt}:reserve:${requestIp(req)}`)}
async function boundedJson(req:Request,max:number){const cl=Number(req.headers.get("content-length")||0);if(Number.isFinite(cl)&&cl>max)throw Object.assign(new Error(),{code:"REQUEST_TOO_LARGE",status:413});const r=req.body?.getReader();if(!r)return {};const chunks:Uint8Array[]=[];let n=0;while(true){const {done,value}=await r.read();if(done)break;if(value){n+=value.byteLength;if(n>max){try{await r.cancel()}catch{};throw Object.assign(new Error(),{code:"REQUEST_TOO_LARGE",status:413})}chunks.push(value)}}const all=new Uint8Array(n);let o=0;for(const c of chunks){all.set(c,o);o+=c.length}try{return n?JSON.parse(new TextDecoder().decode(all)): {}}catch{throw Object.assign(new Error(),{code:"INVALID_JSON",status:400})}}
async function verifyTurnstile(token:unknown,req:Request){const secret=Deno.env.get("TURNSTILE_SECRET_KEY");if(!secret)return false;const value=String(token||"");if(value.length<10||value.length>4096)return false;const b=new URLSearchParams();b.set("secret",secret);b.set("response",value);const ip=requestIp(req);if(ip!=="unknown")b.set("remoteip",ip);let r:Response;try{r=await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify",{method:"POST",body:b,signal:AbortSignal.timeout(TURNSTILE_TIMEOUT_MS)})}catch{return false}if(!r.ok)return false;let x:any;try{x=await r.json()}catch{return false}if(x?.success!==true||String(x?.action||"")!=="reserve_batch")return false;return String(x?.hostname||"").trim().toLowerCase()===EXPECTED_TURNSTILE_HOSTNAME}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({ok:false,code:"METHOD_NOT_ALLOWED"},405);const origin=req.headers.get("origin");if(origin&&origin!==SITE_ORIGIN)return json({ok:false,code:"ORIGIN_NOT_ALLOWED"},403);try{const body=await boundedJson(req,MAX_BODY_BYTES);const canvas=String(body?.canvas||"").toLowerCase();const items=body?.items;if(!["human","ai"].includes(canvas))return json({ok:false,code:"INVALID_CANVAS"},400);if(!Array.isArray(items)||items.length<1||items.length>1000)return json({ok:false,code:"INVALID_ITEM_COUNT"},400);if(!(await verifyTurnstile(body?.turnstile_token,req)))return json({ok:false,code:"BOT_CHECK_FAILED"},403);const s=db();const {data:allowed,error:re}=await s.rpc("consume_reservation_rate_limit",{p_key_hash:await rateKey(req),p_limit:20});if(re)throw re;if(!allowed)return json({ok:false,code:"RATE_LIMITED"},429);const token=randomToken();const {data,error}=await s.rpc("reserve_batch_atomic",{p_canvas:canvas,p_items:items,p_token_hash:await sha256Hex(token),p_created_ip_hash:await rateKey(req),p_ttl_seconds:420});if(error)throw error;if(!data?.ok){const st=data?.code==="CELL_CONFLICT"?409:data?.code==="CANVAS_LOCKED"?423:400;return json(data,st)}return json({...data,reservation_token:token},201)}catch(e:any){if(e?.code==="REQUEST_TOO_LARGE"||e?.code==="INVALID_JSON")return json({ok:false,code:e.code},e.status);console.error(e);return json({ok:false,code:"INTERNAL_ERROR"},500)}});
