import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SITE_ORIGIN="https://ozdalmete-netizen.github.io";
const enc=new TextEncoder();
const uuidRe=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const certRe=/^H1-[A-F0-9]{16}$/i;
const slugRe=/^[a-f0-9]{18}$/i;

function originAllowed(req:Request){const origin=String(req.headers.get("origin")||"");return !origin||origin===SITE_ORIGIN;}
function cors(req:Request){const origin=String(req.headers.get("origin")||"");return {...(origin===SITE_ORIGIN?{"Access-Control-Allow-Origin":SITE_ORIGIN}:{}),"Access-Control-Allow-Headers":"content-type,x-h1-admin-key","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"};}
function json(req:Request,data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer"}});}
function db(){return createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});}
async function digest(v:string){return new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(v)))}
async function digestHex(v:string){return [...await digest(v)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function sameSecret(a:string,b:string){const [x,y]=await Promise.all([digest(a),digest(b)]);if(x.length!==y.length)return false;let diff=0;for(let i=0;i<x.length;i++)diff|=x[i]^y[i];return diff===0;}
function requestIp(req:Request){return req.headers.get("cf-connecting-ip")||req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown";}
async function consumeBadAuthAttempt(req:Request){try{const salt=String(Deno.env.get("RATE_LIMIT_SALT")||"humanity1-admin-auth");const key=await digestHex(`${salt}:admin:${requestIp(req)}`);const {data,error}=await db().rpc("consume_reservation_rate_limit",{p_key_hash:key,p_limit:8});if(error){console.error("admin auth rate limit",error.message);return true}return data===true;}catch(e){console.error("admin auth rate limit",e);return true}}
async function authorized(req:Request){const expected=String(Deno.env.get("H1_ADMIN_KEY")||"");if(expected.length<24)return {ok:false,code:"ADMIN_NOT_CONFIGURED",status:503};const provided=String(req.headers.get("x-h1-admin-key")||"");const validShape=provided.length>=24&&provided.length<=512;const match=validShape&&(await sameSecret(provided,expected));if(match)return {ok:true};const allowed=await consumeBadAuthAttempt(req);if(!allowed)return {ok:false,code:"TOO_MANY_ATTEMPTS",status:429};return {ok:false,code:"UNAUTHORIZED",status:401};}
function cleanText(v:unknown,max=160){return String(v??"").replace(/[\r\n\t]+/g," ").trim().slice(0,max)}

async function dashboard(){const s=db();const {data,error}=await s.rpc("admin_dashboard_summary");if(error)throw error;return {...data,environment:{dodo:String(Deno.env.get("DODO_PAYMENTS_ENVIRONMENT")||"test_mode"),nowpayments_configured:!!Deno.env.get("NOWPAYMENTS_API_KEY"),turnstile_configured:!!Deno.env.get("TURNSTILE_SECRET_KEY"),reset_enabled:String(Deno.env.get("H1_ADMIN_ALLOW_TEST_RESET")||"").toLowerCase()==="true"}};}

async function payments(body:any){const s=db();const limit=Math.min(250,Math.max(1,Number(body?.limit)||100));const offset=Math.max(0,Number(body?.offset)||0);let q=s.from("payments").select("id,batch_id,provider,provider_payment_id,provider_order_id,amount_minor,currency,status,provider_status,pay_currency,pay_amount,actually_paid,paid_at,created_at,updated_at").order("created_at",{ascending:false}).range(offset,offset+limit-1);const provider=cleanText(body?.provider,30).toLowerCase();const status=cleanText(body?.status,30).toLowerCase();if(provider)q=q.eq("provider",provider);if(status)q=q.eq("status",status);const {data:rows,error}=await q;if(error)throw error;const batchIds=[...new Set((rows||[]).map((r:any)=>r.batch_id).filter(Boolean))];let batches:any[]=[];if(batchIds.length){const r=await s.from("checkout_batches").select("id,canvas,item_count,amount_minor,currency,status,country_code,ai_provider,created_at,updated_at").in("id",batchIds);if(r.error)throw r.error;batches=r.data||[];}const byId=new Map(batches.map((b:any)=>[b.id,b]));return {ok:true,rows:(rows||[]).map((r:any)=>({...r,batch:byId.get(r.batch_id)||null})),limit,offset};}

async function search(body:any){const s=db();const raw=cleanText(body?.query,180);if(!raw)return {ok:true,query:raw,marks:[],payments:[],batches:[]};const marks:any[]=[];const pays:any[]=[];const batches:any[]=[];const coord=raw.match(/^(human|ai)\s*[:#]?\s*(\d{1,4})\s*[,x\/]\s*(\d{1,4})$/i);if(coord){const r=await s.from("marks").select("mark_number,canvas,x,y,color_id,country_code,ai_provider,sealed_at,certificate_id,share_slug,batch_id,payment_id").eq("canvas",coord[1].toLowerCase()).eq("x",Number(coord[2])).eq("y",Number(coord[3])).limit(20);if(r.error)throw r.error;marks.push(...(r.data||[]));} else if(/^\d+$/.test(raw)){const r=await s.from("marks").select("mark_number,canvas,x,y,color_id,country_code,ai_provider,sealed_at,certificate_id,share_slug,batch_id,payment_id").eq("mark_number",Number(raw)).limit(20);if(r.error)throw r.error;marks.push(...(r.data||[]));} else if(certRe.test(raw)){const r=await s.from("marks").select("mark_number,canvas,x,y,color_id,country_code,ai_provider,sealed_at,certificate_id,share_slug,batch_id,payment_id").eq("certificate_id",raw.toUpperCase()).limit(20);if(r.error)throw r.error;marks.push(...(r.data||[]));} else if(slugRe.test(raw)){const r=await s.from("marks").select("mark_number,canvas,x,y,color_id,country_code,ai_provider,sealed_at,certificate_id,share_slug,batch_id,payment_id").eq("share_slug",raw.toLowerCase()).limit(20);if(r.error)throw r.error;marks.push(...(r.data||[]));}
  if(uuidRe.test(raw)){const [a,b,c]=await Promise.all([s.from("checkout_batches").select("id,canvas,item_count,amount_minor,currency,status,country_code,ai_provider,expires_at,created_at,updated_at").eq("id",raw).limit(20),s.from("payments").select("id,batch_id,provider,provider_payment_id,provider_order_id,amount_minor,currency,status,provider_status,pay_currency,paid_at,created_at,updated_at").eq("id",raw).limit(20),s.from("payments").select("id,batch_id,provider,provider_payment_id,provider_order_id,amount_minor,currency,status,provider_status,pay_currency,paid_at,created_at,updated_at").eq("batch_id",raw).limit(50)]);for(const r of [a,b,c])if(r.error)throw r.error;batches.push(...(a.data||[]));pays.push(...(b.data||[]),...(c.data||[]));} else {const p1=await s.from("payments").select("id,batch_id,provider,provider_payment_id,provider_order_id,amount_minor,currency,status,provider_status,pay_currency,paid_at,created_at,updated_at").eq("provider_payment_id",raw).limit(20);if(p1.error)throw p1.error;pays.push(...(p1.data||[]));if(!pays.length){const p2=await s.from("payments").select("id,batch_id,provider,provider_payment_id,provider_order_id,amount_minor,currency,status,provider_status,pay_currency,paid_at,created_at,updated_at").eq("provider_order_id",raw).limit(20);if(p2.error)throw p2.error;pays.push(...(p2.data||[]));}}
  const batchIds=[...new Set([...marks.map((m:any)=>m.batch_id),...pays.map((p:any)=>p.batch_id)].filter(Boolean))];if(batchIds.length){const r=await s.from("checkout_batches").select("id,canvas,item_count,amount_minor,currency,status,country_code,ai_provider,expires_at,created_at,updated_at").in("id",batchIds).limit(50);if(r.error)throw r.error;for(const b of r.data||[])if(!batches.some((x:any)=>x.id===b.id))batches.push(b);}return {ok:true,query:raw,marks,payments:[...new Map(pays.map((p:any)=>[p.id,p])).values()],batches:[...new Map(batches.map((b:any)=>[b.id,b])).values()]};}

async function resetPreview(){const s=db();const [m,b,p,r,w]=await Promise.all([s.from("marks").select("id",{count:"exact",head:true}),s.from("checkout_batches").select("id",{count:"exact",head:true}),s.from("payments").select("id",{count:"exact",head:true}),s.from("reservation_cells").select("batch_id",{count:"exact",head:true}),s.from("webhook_events").select("id",{count:"exact",head:true})]);for(const x of [m,b,p,r,w])if(x.error)throw x.error;return {ok:true,locked:true,reason:"DESTRUCTIVE_RESET_NOT_DEPLOYED",environment:String(Deno.env.get("DODO_PAYMENTS_ENVIRONMENT")||"test_mode"),would_delete:{marks:m.count||0,batches:b.count||0,payments:p.count||0,reservation_cells:r.count||0,webhook_events:w.count||0}};}

Deno.serve(async(req)=>{if(!originAllowed(req))return json(req,{ok:false,code:"ORIGIN_NOT_ALLOWED"},403);if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return json(req,{ok:false,code:"METHOD_NOT_ALLOWED"},405);const len=Number(req.headers.get("content-length")||0);if(Number.isFinite(len)&&len>65536)return json(req,{ok:false,code:"REQUEST_TOO_LARGE"},413);try{const auth=await authorized(req);if(!auth.ok)return json(req,auth,auth.status);const body=await req.json().catch(()=>({}));const action=cleanText(body?.action||"dashboard",40).toLowerCase();if(action==="dashboard")return json(req,await dashboard());if(action==="payments")return json(req,await payments(body));if(action==="search")return json(req,await search(body));if(action==="reset_preview")return json(req,await resetPreview());return json(req,{ok:false,code:"UNKNOWN_ACTION"},400);}catch(e){console.error("admin-api",e);return json(req,{ok:false,code:"INTERNAL_ERROR"},500);}});
